{
    "log": [
        {
            "output": "stderr",
            "format": "plain",
            "level": "info"
        }
    ],
    "p2p": {
        "topics_of_interest": {
            "messages": "high",
            "blocks": "high"
        },
        "listen_address": "/ip4/0.0.0.0/tcp/4000",
        "public_address": "/ip4/87.62.101.32/tcp/4000",
        "trusted_peers": [
            {
                "address": "/ip4/13.56.0.226/tcp/3000",
                "id": "7ddf203c86a012e8863ef19d96aabba23d2445c492d86267"
            },
            {
                "address": "/ip4/3.125.183.71/tcp/3000",
                "id": "9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67"
            },
            {
                "address": "/ip4/3.125.31.84/tcp/3000",
                "id": "8f9ff09765684199b351d520defac463b1282a63d3cc99ca"
            },
            {
                "address": "/ip4/18.182.115.51/tcp/3000",
                "id": "8529e334a39a5b6033b698be2040b1089d8f67e0102e2575"
            },
            {
                "address": "/ip4/18.177.78.96/tcp/3000",
                "id": "fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9"
            },
            {
                "address": "/ip4/52.9.132.248/tcp/3000",
                "id": "671a9e7a5c739532668511bea823f0f5c5557c99b813456c"
            },
            {
                "address": "/ip4/52.8.15.52/tcp/3000",
                "id": "18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5"
            }
        ]
    },
    "rest": {
        "listen": "127.0.0.1:3300"
    },
    "storage": "../storage",
}